version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  rext:
    build:
      context: ./
      dockerfile: ./apps/rext/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usuario/app/rext
      - /usuario/app/rext/node_modules
    command: npm run start:dev rext

  gert:
    build:
      context: ./
      dockerfile: ./apps/gert/Dockerfile
    ports:
      - '4000:5000'
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - rext
    volumes:
      - .:/usuario/app/rext
      - /usuario/app/rext/node_modules
    command: npm run start:dev gert

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data

  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '15432:80'
